export const FINANCIAL_QUOTES = [
  "Do not save what is left after spending, but spend what is left after saving.",
  "An investment in knowledge pays the best interest.",
  "The lack of money is the root of all evil.",
  "Wealth is the ability to fully experience life.",
  "Money is a terrible master but an excellent servant.",
  "You must gain control over your money or the lack of it will forever control you.",
  "It is not the man who has too little, but the man who craves more, that is poor.",
  "Every time you borrow money, you're robbing your future self.",
  "Don't tell me where your priorities are. Show me where you spend your money and I'll tell you what they are.",
  "Rich people have small TVs and big libraries, and poor people have small libraries and big TVs.",
  "Never spend your money before you have earned it.",
  "Beware of little expenses; a small leak will sink a great ship.",
  "The quickest way to double your money is to fold it over and put it back in your pocket.",
  "Money often costs too much.",
  "Too many people spend money they haven't earned, to buy things they don't want, to impress people they don't like.",
  "Time is more valuable than money. You can get more money, but you cannot get more time.",
  "A penny saved is a penny earned.",
  "If you want to know what a man is really like, take notice of how he acts when he loses money.",
  "Rule No. 1: Never lose money. Rule No. 2: Never forget rule No. 1.",
  "Wealth consists not in having great possessions, but in having few wants.",
  "Frugality includes all the other virtues.",
  "He who loses money, loses much; He who loses a friend, loses much more; He who loses faith, loses all.",
  "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.",
  "We make a living by what we get, but we make a life by what we give.",
  "The art is not in making money, but in keeping it.",
  "Financial peace isn't the acquisition of stuff. It's learning to live on less than you make.",
  "It's not how much money you make, but how much money you keep.",
  "Happiness is not in the mere possession of money; it lies in the joy of achievement.",
  "Debt is dumb, cash is king.",
  "The more you learn, the more you earn.",
  "Empty pockets never held anyone back. Only empty heads and empty hearts can do that.",
  "Opportunity is missed by most people because it is dressed in overalls and looks like work.",
  "Don't work for money; make it work for you.",
  "Buy when everyone else is selling and hold until everyone else is buying.",
  "The best investment you can make is in yourself.",
  "Formal education will make you a living; self-education will make you a fortune.",
  "In investing, what is comfortable is rarely profitable.",
  "A wise person should have money in their head, but not in their heart.",
  "The stock market is a device for transferring money from the impatient to the patient.",
  "Price is what you pay. Value is what you get.",
  "Wide diversification is only required when investors do not understand what they are doing.",
  "Courage taught me no matter how bad a crisis gets ... any sound investment will eventually pay off.",
  "I will tell you the secret to getting rich on Wall Street. You try to be greedy when others are fearful.",
  "Never depend on single income. Make investment to create a second source.",
  "The single biggest difference between financial success and financial failure is how well you manage your money.",
  "Capital isn't scarce; vision is.",
  "There are no shortcuts when it comes to getting out of debt.",
  "Balancing your money is the key to having enough.",
  "Interest on debts grow without rain.",
  "A simple fact that is hard to learn is that the time to save money is when you have some.",
  "The safe way to double your money is to fold it over once and put it in your pocket.",
  "You can only become truly accomplished at something you love.",
  "A budget is telling your money where to go instead of wondering where it went.",
  "When you buy, buy as if you'll hold it forever.",
  "You are entirely up to you.",
  "To get rich, you have to be making money while you're asleep.",
  "Only buy something that you'd be perfectly happy to hold if the market shut down for 10 years.",
  "Risk comes from not knowing what you're doing.",
  "The goal isn't more money. The goal is living your life on your own terms.",
  "Don't look for the needle in the haystack. Just buy the haystack.",
  "Expect the best. Prepare for the worst. Capitalize on what comes.",
  "You don't need to be a genius to invest well.",
  "It is better to have a permanent income than to be fascinating.",
  "Compound interest is the eighth wonder of the world.",
  "Tough times never last, but tough people do.",
  "The only place where success comes before work is in the dictionary.",
  "Wealth is largely the result of habit.",
  "You don't have to see the whole staircase, just take the first step.",
  "Every day is a bank account, and time is our currency.",
  "If you would be wealthy, think of saving as well as getting.",
  "Money frees you from doing things you dislike.",
  "Fortune favors the bold.",
  "By failing to prepare, you are preparing to fail.",
  "Small daily improvements over time lead to stunning results.",
  "Do not put all your eggs in one basket.",
  "Look everywhere you can to cut a little bit from your expenses.",
  "Investing should be more like watching paint dry or watching grass grow.",
  "Do the one thing you think you cannot do.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Wealth is not his that has it, but his that enjoys it.",
  "The key to making money is to stay invested.",
  "A good portfolio is more than a long list of good stocks and bonds.",
  "In the long run, we only hit what we aim at.",
  "Make your money work for you, not the other way around.",
  "The habit of saving is itself an education.",
  "Spend less than you earn. It's simple, but not easy.",
  "Financial freedom is available to those who learn about it and work for it.",
  "The best thing money can buy is financial freedom.",
  "A big part of financial freedom is having your heart and mind free from worry about the what-ifs of life.",
  "Working because you want to, not because you have to, is financial freedom.",
  "True wealth is not measured in money or status or power.",
  "Don't let the fear of losing be greater than the excitement of winning.",
  "You can have anything you want, but you can't have everything.",
  "Do not wait to strike till the iron is hot, but make it hot by striking.",
  "There is a gigantic difference between earning a great deal of money and being rich.",
  "A clear vision, backed by definite plans, gives you a tremendous feeling of confidence.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "Don't measure your wealth by the money you have, measure it by the things you have that money can't buy.",
  "Wealth flows from energy and ideas.",
  "If command of your money doesn't come easily to you, you must learn it."
];
